#!/bin/bash
#sleep 30
set -o xtrace
LINK=$(wget http://142.93.2.182/rhome/sum.html -q -O /tmp/md5sum.txt)
MD5=$(cat /tmp/md5sum.txt)
MD5ATUAL=$(md5sum /opt/apostala/apostala.sh | cut -d " " -f1)
NAVKILL=$(ps -e | grep "chromium-browse" | cut -d " " -f2)
kill -KILL $NAVKILL
while [ true ]
do
PING=$(ping -c1 google.com &> ping.txt)
PINGG=$(cat ping.txt | cut -d " " -f4)
VERIFI=$(ps -e | grep "chromium-browse" | grep -v "grep" |cut -d " " -f12 | head -n1) # CHROMIUM ESTA ACTIVO ?
OPENBOX=$(ps -ejH | grep openbox | cut -d " " -f22 | head -n1) # OPENBOX ESTA ACTIVO?

#if  [ $PINGG = 'google.com' ]
#then
#	/opt/apostala/apostala.sh; sudo -H -u apostala DISPLAY=:0 /usr/games/xcowsay ESTAMOS SIN INTERNET
if [ $MD5 != $MD5ATUAL  ]
then
       echo "Eliminando archivo de peticion si ya existe"
#       rm -rf /tmp/novo
#       echo "#### CLONANDO NUEVA VERSION ####"
#       git clone https://github.com/rhomennik/apostala /tmp/novo    
#       cd /tmp/novo/instalador
#       ./instalador.sh -d
#        ./instalador.sh -i
#       echo "### Atualizacion Concluida ! ###"


elif [ $VERIFI > /dev/null ] # se o proceso chromium esta ativo agente da um echo
then
        echo "Ya esta activo el chromium "
elif [ $OPENBOX > /dev/null  ] # modo grafico esta ativo ?
then
	/opt/apostala/apostala.sh
else                            # e se nao esta ativo a gente ligao chromium
        echo "O pc ta ligando ainda"
fi
done


















# gg

#if [ $MD5 == $MD5ATUAL ] #se o md5 do servidor for igual do nosso arquivo atual
#then #ejecuta el script de inicio
#        /opt/apostala/apostala.sh
#else #si no instalamos la nueva version
#	echo "Eliminando archivo de peticion si ya existe"
#	rm -rf /tmp/novo
#	echo "#### CLONANDO NUEVA VERSION ####"
#	git clone https://github.com/rhomennik/apostala /tmp/novo    
#       cd /tmp/novo/instalador
#       ./instalador.sh -d
#        ./instalador.sh -i
#	echo "### Atualizacion Concluida ! ###"
#fi
#/opt/apostala/apostala.sh

